import styles from "./TextTraces.module.scss"
import cn from "classnames";
import React, { useState, useEffect, useRef } from "react";
import { useIntervalWhen } from "rooks";
import { randomInt } from "/lib/utils";

export default function TextTraces({ event, view }) {

	if (view !== 'event' || !event || event.participant.slug !== 'camila-marambio') return null
	const [line, setLine] = useState()
	useIntervalWhen(() => setLine(traces[randomInt(0, traces.length - 1)]), 6000, true, true); // Update active state of events client side

	return (
		<div className={styles.textTraces}>
			{line && <div className={styles.line}>{line}</div>}
		</div>
	);
}


const traces = ['Your time might be running out but Time itself never runs out.',
	'“Time is not even, Space is not empty.” Eiko & Koma',
	'You are not the violence you suffer.',
	'Controlled Continuous Fusion.',
	'The act of imagining is necessary. Imagining is different from a matter of fact.',
	'Dying is hard to learn.',
	'Seeing the dying as subject.',
	'Attending dying is learning about death and dying.',
	'Not existing any more is dying. Existence of non-existence.',
	'Body memory is memory of experience.',
	'If you have enough stimulus, you’ll remember.',
	'“It’s new to me forever.” Eiko Otake',
	'Internalized repulsion is conditioned by my own bias.',
	'Rediscover your biases.',
	'A bias comes from experience, it is not chosen by itself.',
	'If you study your biases, you can choose which ones to hold on to.',
	'What are my biases?',
	'Move not like humans.',
	'Teaching body-based democracy.',
	'Dying is a movement of ing. A death does not only happen when a death is proclaimed.',
	'Opening up the possibility to cease, momentarily, to be human, maybe.',
	'Humbleness is a softness that is powered by experience.',
	'Hardness is a bias.',
	'Protest, resist.',
	'Mushy Jell-O.',
	'A Jell-O made with too much water.',
	'Lingering to taste more… be unproductive.',
	'Fleeting dreams.',
	'Rest in the grey zone, paying attention to detail for no reason at all.',
	'No meaning.',
	'Breathe out. Sound of the little dream.',
	'Enjoy being stuck by noticing that there is always something that can move, might move.',
	'Resting is a political act.',
	'To protest by laying on the ground and being alive; not dead (yet).',
	'In continuous movement, detail to detail, without holding.',
	'Murky.',
	'Undoing exercise to find delicious movement.',
	'Between this and that.',
	'Linger between the tensions, feeling into the potential of movement.',
	'Un-behave.',
	'De-imagine.',
	'Un-imagine.',
	'De-function',
	'Form not fitting to content.',
	'Change is a continual process.',
	'Poetics of space, place and time intermingle.',
	'A curation is a choreography.',
	'Self-curation.',
	'I like to play, I always have.',
	'Swirl, swing, spring, jump, run, swim.',
	'Look, follow, listen, serve, give into drift of the as yet unknow.',
	'End of nothing.',
	'I can be in the present.',
	'I am pliable.',
	'I am observed curiously, no-sense.',
	'Inner listening, outer eyesight, inner tears, outer silence, exterior colors, warm availability.',
	'Seeking eyes, thinking mind, moving pencil, shaking tail.',
	'Full body of love.',
	'Lips smacking together in pleasure.',
	'Erotic Stillness.',
	'The pace of respect.',
	'The intensity of giving.',
	'Usability is different than productivity.',
	'We often seek change by destruction. What if we changed without destroying?',
	'Questions, complaints, problems?',
	'Sleep, bed, shadow.',
	'I am lover.',
	'I love myself, not me, but the life I see.',
	'I have had countless beds since my childhood.',
	'Chicago. Chicago. Chicago.',
	'Atom bomb, jazz, and the neoliberal experiment.',
	'Was I a boy then?',
	'He is growing old and I drift away, with sadness.',
	'Those whose shadow can’t be returned to are left adrift.',
	'The memory of everything I was.',
	'I do not miss what I was I miss what I missed.',
	'“Lucky me,” we though in our naked encounter.',
	'Gentle pressure.',
	'The bed that cracked under the weight if our unrealizable love.',
	'Minds meeting. One moves on and the other joins its twin.',
	'Lingering in the unmeet desire.',
	'I will share the emptiness.',
	'The possibility to speak.',
	'Write a letter.',
	'Desires enriched by hesitation.',
	'Conflict provides negotiation.',
	'“We can linger, it is a human right. It is the right of the wind, sky, tree. They linger.” Eiko Otake',
	'“Taking time to finish is a form of resistance.” Eiko Otake',
	'Practice of dying.',
	'The dignity of commitment.',
	'Pre-school, knotting, tension, survey, crawl, be caressed by your grandmother.',
	'Joints where you don’t have them.',
	'“Body is a landscape; Landscape is a body.” Eiko Otake',
	'Momentary power.',
	'“Distance is malleable.” Eiko Otake',
	'Becoming not to become but becoming.',
	'Today, I am vulnerable.',
	'Be available.']